//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

use async_graphql::SimpleObject;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, SimpleObject)]
#[sea_orm(table_name = "reactions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub slot: i32,
    pub reaction_value: i32,
    pub sender_wallet: String,
    pub reaction_type: String,
    pub reacted_to: String,
    pub timestamp: DateTime,
    pub tx_signature: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
