//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

use async_graphql::SimpleObject;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, SimpleObject)]
#[sea_orm(table_name = "track_trending_scores")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub track_id: i32,
    pub r#type: String,
    pub genre: Option<String>,
    pub version: String,
    pub time_range: String,
    #[sea_orm(column_type = "Double")]
    pub score: f64,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
