//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ursm_content_nodes")]
pub struct Model {
    pub blockhash: Option<String>,
    pub blocknumber: Option<i32>,
    pub created_at: DateTime,
    #[sea_orm(primary_key, auto_increment = false)]
    pub is_current: bool,
    #[sea_orm(primary_key, auto_increment = false)]
    pub cnode_sp_id: i32,
    pub delegate_owner_wallet: String,
    pub owner_wallet: String,
    pub proposer_sp_ids: Vec<i32>,
    pub proposer_1_delegate_owner_wallet: String,
    pub proposer_2_delegate_owner_wallet: String,
    pub proposer_3_delegate_owner_wallet: String,
    pub endpoint: Option<String>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub txhash: String,
    pub slot: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::blocks::Entity",
        from = "Column::Blockhash",
        to = "super::blocks::Column::Blockhash",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Blocks2,
    #[sea_orm(
        belongs_to = "super::blocks::Entity",
        from = "Column::Blocknumber",
        to = "super::blocks::Column::Number",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Blocks1,
}

impl ActiveModelBehavior for ActiveModel {}
