//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ursm_content_nodes")]
pub struct Model {
    pub blockhash: Option<String>,
    pub blocknumber: Option<i32>,
    pub created_at: DateTime,
    pub is_current: bool,
    #[sea_orm(primary_key)]
    pub cnode_sp_id: i32,
    pub delegate_owner_wallet: String,
    pub owner_wallet: String,
    pub proposer_sp_ids: Option<Json>,
    pub proposer_1_delegate_owner_wallet: String,
    pub proposer_2_delegate_owner_wallet: String,
    pub proposer_3_delegate_owner_wallet: String,
    pub endpoint: Option<String>,
    pub txhash: String,
    pub slot: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
