//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

use async_graphql::SimpleObject;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, SimpleObject)]
#[sea_orm(table_name = "user_challenges")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub challenge_id: String,
    pub user_id: i32,
    pub specifier: String,
    pub is_complete: bool,
    pub current_step_count: Option<i32>,
    pub completed_blocknumber: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
